import { useCallback, useEffect, useRef, useState } from 'react';
import exifr from 'exifr';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

type Metadata = Record<string, any>;
type Photo = { file: File; data: Metadata | null; previewUrl: string; loading: boolean; error?: string };
const OPTIONS = { tiff: true, xmp: true, icc: true, iptc: true, jfif: true, ihdr: true, gps: true, reviveValues: true };

const bytes = (n: number) => { if (!n) return '0 Bytes'; const u=['Bytes','KB','MB','GB']; const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3); return `${(n/1024**i).toFixed(2)} ${u[i]}`; };
const json = (d: Metadata) => JSON.stringify(d, (_k,v) => v instanceof Uint8Array || v instanceof ArrayBuffer ? `[Binary Buffer (${v.byteLength} bytes)]` : v, 2);
const date = (d: Metadata|null) => { const v=d?.DateTimeOriginal||d?.CreateDate||d?.ModifyDate; if(!v)return 'N/A'; const x=v instanceof Date?v:new Date(v); return Number.isNaN(x.getTime())?String(v):x.toLocaleString(); };
const dims = (d: Metadata|null) => { const w=d?.ExifImageWidth||d?.ImageWidth||d?.rawImageWidth,h=d?.ExifImageHeight||d?.ImageHeight||d?.rawImageHeight; return w&&h?`${w} × ${h} px`:'N/A'; };
const shutter = (d: Metadata|null) => { const v=d?.ExposureTime; return typeof v==='number'?(v<1?`1/${Math.round(1/v)}s`:`${v}s`):'N/A'; };

async function readFiles(files: File[], urls: string[]) {
  const out: Photo[] = new Array(files.length); let cursor=0;
  async function worker(){ while(cursor<files.length){ const i=cursor++,file=files[i]; try{ const data=await exifr.parse(file,OPTIONS); out[i]={file,data:data||{},previewUrl:urls[i],loading:false}; }catch(e){ out[i]={file,data:null,previewUrl:urls[i],loading:false,error:e instanceof Error?e.message:'Could not read metadata.'}; } } }
  await Promise.all(Array.from({length:Math.min(2,files.length)},worker)); return out;
}

function App(){
  const [photos,setPhotos]=useState<Photo[]>([]),[selected,setSelected]=useState(0),[dragging,setDragging]=useState(false),[status,setStatus]=useState('');
  const [address,setAddress]=useState(''); const input=useRef<HTMLInputElement>(null),mapEl=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),marker=useRef<L.Marker|null>(null);
  const add=useCallback(async(files:FileList|File[])=>{ const fs=Array.from(files).filter(f=>f.type.startsWith('image/')||/\.(heic|heif|tiff|webp)$/i.test(f.name)); if(!fs.length){setStatus('No supported image files were found.');return;} const urls=fs.map(f=>URL.createObjectURL(f)); const start=photos.length; setPhotos(p=>[...p,...fs.map((file,i)=>({file,data:null,previewUrl:urls[i],loading:true}))]); setSelected(start); setStatus(`Reading ${fs.length} photo${fs.length===1?'':'s'}...`); const parsed=await readFiles(fs,urls); setPhotos(p=>{const next=[...p]; parsed.forEach((x,i)=>{if(next[start+i])next[start+i]=x;});return next;}); setStatus(`${parsed.length} photo${parsed.length===1?'':'s'} loaded.`);},[photos.length]);
  useEffect(()=>{const onPaste=(e:ClipboardEvent)=>{const f=Array.from(e.clipboardData?.files||[]).filter(x=>x.type.startsWith('image/'));if(f.length){e.preventDefault();void add(f);}};window.addEventListener('paste',onPaste);return()=>window.removeEventListener('paste',onPaste);},[add]);
  const photo=photos[selected],data=photo?.data,hasGps=typeof data?.latitude==='number'&&typeof data?.longitude==='number';
  useEffect(()=>{if(!mapEl.current||!hasGps){map.current?.remove();map.current=null;marker.current=null;return;}const p=[data!.latitude,data!.longitude] as [number,number];if(!map.current){map.current=L.map(mapEl.current).setView(p,14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map.current);marker.current=L.marker(p).addTo(map.current);}else{map.current.setView(p,14);marker.current?.setLatLng(p);map.current.invalidateSize();}},[selected,hasGps,data]);
  useEffect(()=>{setAddress('');if(!hasGps)return;const c=new AbortController();fetch(`https://nominatim.openstreetmap.org/reverse?format=json&lat=${data!.latitude}&lon=${data!.longitude}&zoom=18&addressdetails=1`,{headers:{'Accept-Language':'en'},signal:c.signal}).then(r=>r.json()).then(r=>setAddress(r.display_name||'Coordinates found; location unavailable.')).catch(()=>setAddress('Coordinates found; reverse geocoding unavailable.'));return()=>c.abort();},[selected,hasGps,data]);
  const remove=(i:number)=>setPhotos(p=>{URL.revokeObjectURL(p[i]?.previewUrl);const n=p.filter((_,x)=>x!==i);setSelected(s=>Math.min(s>i?s-1:s,Math.max(0,n.length-1)));return n;});
  const clear=()=>{photos.forEach(p=>URL.revokeObjectURL(p.previewUrl));map.current?.remove();map.current=null;setPhotos([]);setSelected(0);setStatus('');};
  const exportOne=()=>{if(!photo||!data)return;const u=URL.createObjectURL(new Blob([json(data)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`exif_${photo.file.name.replace(/\.[^/.]+$/,'')}.json`;a.click();URL.revokeObjectURL(u);};
  const strip=()=>{if(!photo)return;const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d')?.drawImage(img,0,0);c.toBlob(b=>{if(!b)return;const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`clean_${photo.file.name.replace(/\.[^/.]+$/,'')}.jpg`;a.click();URL.revokeObjectURL(u);},'image/jpeg',.92)};img.src=photo.previewUrl;};
  return <div className="page"><div className="shell">
    <header className="neo header"><div><span className="eyebrow">CLIENT-SIDE // MOBILE-READY</span><h1>EXIF INSPECTOR</h1><p>Cross-platform metadata decoder for Android, iOS & Desktop.</p></div><div className="badges"><span>HEIC</span><span>JPEG</span><span>TIFF</span><span>PNG</span></div></header>
    <section className={`neo upload ${dragging?'active':''}`} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);void add(e.dataTransfer.files)}}><input ref={input} type="file" accept="image/*,.heic,.heif,.tiff,.webp" multiple hidden onChange={e=>{if(e.target.files)void add(e.target.files);e.currentTarget.value=''}}/><div className="plus">+</div><h2>CHOOSE OR DROP PHOTOS</h2><p>Paste with ⌘V / Ctrl+V · Multiple files supported · Files remain 100% local.</p></section>
    {status&&<div className="neo status">⚠️ <span>{status}</span></div>}
    {photos.length>0&&<main className="content">
      <div className="toolbar"><button className="btn violet" onClick={exportOne}>💾 SAVE FULL JSON REPORT</button><button className="btn green" onClick={strip}>🛡️ DOWNLOAD PRIVACY COPY</button><button className="btn red" onClick={clear}>✕ CLEAR ALL</button></div>
      <section className="neo queue"><div className="queue-head"><strong>PHOTO QUEUE</strong><div className="queue-actions"><span>{photos.length} LOADED</span><button className="queue-btn" onClick={()=>input.current?.click()}>+ ADD MORE</button></div></div><div className="thumbs">{photos.map((p,i)=><div className={`thumb-wrap ${i===selected?'selected':''}`} key={`${p.file.name}-${i}`}><button className="thumb" onClick={()=>setSelected(i)}><img src={p.previewUrl} alt=""/><span>{i+1}</span></button><button className="remove-thumb" onClick={()=>remove(i)}>×</button></div>)}</div></section>
      <section className="neo batch"><div className="card-head"><h3>▦ ALL PHOTOS — METADATA</h3><span>{photos.reduce((n,p)=>n+Object.keys(p.data||{}).length,0)} TAGS</span></div><div className="batch-list">{photos.map((p,i)=><article className={`batch-card ${i===selected?'selected':''}`} key={`meta-${p.file.name}-${i}`}><div className="batch-top" onClick={()=>setSelected(i)}><img src={p.previewUrl} alt={p.file.name}/><div className="batch-info"><strong>{p.file.name}</strong><span>{bytes(p.file.size)} · {p.loading?'READING...':`${Object.keys(p.data||{}).length} tags`}</span><span>{p.data?.Make||'Unknown make'} {p.data?.Model||''}</span><span>{date(p.data)}</span><span>{typeof p.data?.latitude==='number'?'📍 GPS':'○ No GPS'}</span></div></div><details><summary>VIEW ALL METADATA</summary>{p.loading?<p className="loading">Reading metadata…</p>:p.data?<pre>{json(p.data)}</pre>:<p>{p.error||'No metadata records detected.'}</p>}</details></article>)}</div></section>
      {photo&&<><section className="neo card"><div className="card-head"><h3>▣ PHOTO PREVIEW & METADATA</h3><span>{bytes(photo.file.size)}</span></div><div className="preview-grid"><div className="preview"><img src={photo.previewUrl} alt={photo.file.name} onError={e=>{e.currentTarget.style.display='none';e.currentTarget.parentElement?.classList.add('preview-error')}}/><span className="preview-error-text">Preview unavailable for this format/browser.</span></div><div className="facts"><Fact label="FILE NAME" value={photo.file.name}/><div className="two"><Fact label="MIME TYPE" value={photo.file.type||'binary image'}/><Fact label="IMAGE DIMENSIONS" value={dims(data)}/></div><Fact label="TIMESTAMP (ORIGINAL)" value={date(data)}/><div className="two"><Fact label="ORIENTATION" value={data?.Orientation?String(data.Orientation):'N/A'}/><Fact label="SOFTWARE" value={data?.Software||'N/A'}/></div></div></div></section><div className="columns"><section className="neo card"><div className="card-head"><h3>◉ GEOLOCATION TELEMETRY</h3><span className={hasGps?'good':'bad'}>{hasGps?'GPS ACTIVE':'NO GPS FOUND'}</span></div><div className="two"><Fact label="LATITUDE" value={hasGps?data!.latitude.toFixed(6):'NOT EMBEDDED'}/><Fact label="LONGITUDE" value={hasGps?data!.longitude.toFixed(6):'NOT EMBEDDED'}/><Fact label="ALTITUDE" value={typeof data?.GPSAltitude==='number'?`${data.GPSAltitude.toFixed(1)} m`:'N/A'}/><Fact label="GPS TIMESTAMP" value={data?.GPSTimeStamp?String(data.GPSTimeStamp):'N/A'}/></div>{hasGps&&<><div ref={mapEl} className="map"/><div className="address">{address||'Resolving location...'}</div><Fact label="MAPS LINK" value="External Map ↗" href={`https://www.google.com/maps?q=${data!.latitude},${data!.longitude}`}/></>}</section><section className="neo card pink"><div className="card-head"><h3>● OPTICAL PROFILE</h3></div><div className="specs"><Fact label="MAKE" value={data?.Make||'N/A'}/><Fact label="MODEL" value={data?.Model||'N/A'}/><Fact label="LENS" value={data?.LensModel||data?.LensInfo||'N/A'}/><Fact label="APERTURE" value={data?.FNumber?`ƒ/${data.FNumber}`:'N/A'}/><Fact label="SHUTTER" value={shutter(data)}/><Fact label="ISO" value={data?.ISO||data?.ISOSpeedRatings||'N/A'}/><Fact label="FOCAL LENGTH" value={data?.FocalLength?`${data.FocalLength} mm`:'N/A'}/><Fact label="FLASH" value={data?.Flash||'N/A'}/><Fact label="COLOR SPACE" value={data?.ColorSpace===1?'sRGB':data?.ColorSpace||'Uncalibrated'}/><Fact label="WHITE BALANCE" value={data?.WhiteBalance||'N/A'}/><Fact label="METERING" value={data?.MeteringMode||'N/A'}/><Fact label="EXPOSURE MODE" value={data?.ExposureMode||'N/A'}/></div></section></div></>}
    </main>}
  </div></div>;
}
function Fact({label,value,href}:{label:string;value:string;href?:string}){return <div className="fact"><small>{label}</small>{href?<a href={href} target="_blank" rel="noreferrer">{value}</a>:<strong>{value}</strong>}</div>}
export default App;
